### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-marinarodriguez#1]
Really cool job @marinarodriguez  !!!

Here you have some tips to improve the exercise:

- [x] Your 'getRandomNumber' function is ok, but I would like you to practice having a function that returns something, executing it, and storing the returned value into a constant ;) Give it a try.
- [x] There is something wrong in your if/else. If you remove the block under 'randomNumber > writtenNumber' condition, any smaller number match as the winning one. Review strict equality conditional and remember to parse input value to a number.
- [x] No need to add ';' at the end on function declarations.
- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "hintEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'hintEl'?
- [x] Remove comments
- [x] Define a good structure of folders and files for the project

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by marinarodriguez** [comment]
I think is ready to review! I've made some improvements, and I will continue trying to make it more appealing!

**Comment by nasivuela** [comment]
This is a well-done work!

I'm closing this, but as always with the last suggestion: you have a couple of small functions, a good opportunity to practice one-line arrow functions, without the brackets and with implicit return ;)

![](https://media.giphy.com/media/24G0CuE3ym8iLooGrR/giphy.gif)
